### ISSUE TITLE
Why not use `gx`?

### ISSUE THREAD

**Issue by scribu** [henrik/vim-open-url#2]
Vim 7.4 has a built-in `gx` binding: `:help gx`.

Note that the default Vim shipped with OS X is 7.3, so you will need to do `brew install vim` or use some other update method.

**Comment by felippenardi** [comment]
Just to note, `:'<,'>norm gx` should open several URLs at the same time.

**Comment by henrik** [comment]
@felippenardi Thank you. Still will only open the first URL on each line though. If one line contains two URLs, the last one won't be opened.

**Comment by felippenardi** [comment]
@henrik Then this is nice :+1:  :)
