### ISSUE TITLE
Does not work in Ubuntu on WSL2

### ISSUE THREAD

**Issue by whytong** [henrik/vim-open-url#5]
Installed it for Vim 8.1 in Ubuntu on Windows Subsystem Linux 2. Upon invoking it says
```
Sorry, the 'Open URL' plugin requires Ruby support.
```
But ruby is already installed in the system 
```
ruby is already the newest version (1:2.7+1).
```

**Comment by whytong** [comment]
Does this work only on MacOS/OS X?

**Comment by henrik** [comment]
Hi! Yes, Mac only I’m afraid, by default. README says so, I think, but it could probably be clearer :)

Perhaps it can be configured to use another program that works on another system. Haven’t touched this code in quite a while.

Vim needs to be compiled with Ruby support, which is not the same thing as having Ruby installed on the system. Try “:ruby p Time.now” inside Vim to confirm your Vim was compiled with Vim support.
